version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: web
    restart: always
    volumes:
      - ./:/usr/src/app
    ports:
      - "3000:3000"
